// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4NrdIQUlZ2Tv6X56QWcTj687FLZMDzog',
    appId: '1:827681075266:web:bd5e452d970877e3c5bddb',
    messagingSenderId: '827681075266',
    projectId: 'app-articles-339e5',
    authDomain: 'app-articles-339e5.firebaseapp.com',
    storageBucket: 'app-articles-339e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2c6VBHGVbIpi7O4_wvZKMtjYSXCsTMU',
    appId: '1:827681075266:android:8e47077553a6b49dc5bddb',
    messagingSenderId: '827681075266',
    projectId: 'app-articles-339e5',
    storageBucket: 'app-articles-339e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCti9fbu1fZ3jXXNHBvJR0T6noFCo_GwhY',
    appId: '1:827681075266:ios:3aec92cd86939a1bc5bddb',
    messagingSenderId: '827681075266',
    projectId: 'app-articles-339e5',
    storageBucket: 'app-articles-339e5.firebasestorage.app',
    iosBundleId: 'com.alejandr.new',
  );
}
